# Golangの公式イメージを使用（バージョンは必要に応じて変更）
FROM golang:1.22

# 必要なツールのインストール
RUN apt-get update && \
    apt-get install -y ffmpeg mpg123 && \
    rm -rf /var/lib/apt/lists/*

# ワーキングディレクトリを設定
WORKDIR /app

# プロジェクトのファイルをコンテナにコピー
COPY . .

# Goモジュールの依存関係をインストール
RUN go mod download

# アプリケーションのビルド
RUN go build -o discordbot main.go

# コンテナ起動時に実行されるコマンド
CMD ["./discordbot"]
